[package]
name = "memory-practice"
version = "0.1.0"
edition = "2021"

[dependencies]
piston_window = "0.117"
piston2d-graphics = "0.39"
rand = "0.8"
mimalloc = "0.1.43"
instant = "0.1"
coarsetime = "0.1.35"
libc = "0.2.169"

